# Generated by Django 4.0.3 on 2022-03-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('odjectid', models.CharField(max_length=255, verbose_name='ID объекта')),
                ('datetime', models.DateTimeField(verbose_name='Дата проезда')),
                ('vehicle_class', models.CharField(max_length=255, verbose_name='Класс')),
                ('zone', models.TextField(verbose_name='Точки фиксации')),
                ('speed', models.CharField(max_length=255, verbose_name='Скорость')),
                ('length', models.CharField(max_length=255, verbose_name='Габариты')),
            ],
            options={
                'db_table': 'radar',
                'managed': False,
            },
        ),
    ]
